{ Common strings }

RSAcceptableMessageCountThreshold = 'Messages count acceptable threshold: %d';
RSConfigWasGenerated = 'Config was generated.';
RSEditConfigManually = 'Edit config manually.';
RSHelpSuggestion = 'Use "%s" to get help.';
RSNoVersionInfoAvailable = '<no version info available>';
RSPreparingWorkflow = 'Preparing workflow...';
RSTerminatingWithExitCode = 'Terminating with exit code %d.';
RSTotalDuration = 'Total duration is %s';
RSTotalMessages = 'Total messages: %d';
RSWorkflowPrepared = 'Workflow prepared.';

{ Execution states }

RSExtractingProjects = 'Extracting projects...';
RSProjectsExtracted = 'Projects extracted.';
//
RSExcludingProjects = 'Excluding projects...';
RSProjectExcluded = 'Project excluded: %s';
RSProjectsExcluded = 'Projects excluded.';
//
RSRunningFixInsight = 'Code analysis in progress...';
RSFixInsightRan = 'Code analysis finished.';
//
RSParsingReports = 'Parsing reports...';
RSReportNotFound = 'Report not found for project: %s';
RSReportsParsed = 'Reports parsed.';
//
RSExcludingUnits = 'Excluding units...';
RSUnitExcluded = 'Unit excluded: %s';
RSUnitsExcluded = 'Units excluded.';
//
RSBuildingReport = 'Building report...';
RSReportBuilt = 'Report built.';
//
RSMakingArchive = 'Making archive...';
RSArchiveMade = 'Archive made.';
//
RSTerminating = 'Terminating...';
RSTerminated = 'Terminated.';

{ Exceptions }

RSApplicationExecutionFailed = 'Application execution failed.';
RSCLIOptionsProcessingFailed = 'Command-line options processing failed.';
RSErroneousConfigSpecified = 'Erroneous config was specified.';
RSNoValidConfigSpecified = 'No valid config was specified.';
RSUnableToGenerateConfig = 'Unable to generate config.';
RSUnknownInputFileType = 'Unknown input file type.';
