{ Common strings }

RSAcceptableMessageCountThreshold = 'Порог допустимого кол-ва сообщений статического анализа: %d';
RSConfigWasGenerated = 'Файл конфигурации был сгенерирован.';
RSEditConfigManually = 'Рекомендуется вручную отредактировать файл конфигурации.';
RSHelpSuggestion = 'Для получения помощи используйте "%s".';
RSNoVersionInfoAvailable = '<информация о версии недоступна>';
RSPreparingWorkflow = 'Подготовка к запуску...';
RSTerminatingWithExitCode = 'Приложение завершается с кодом %d.';
RSTotalDuration = 'Общая длительность работы составила %s';
RSTotalMessages = 'Итого сообщений статического анализа: %d';
RSWorkflowPrepared = 'Подготовка к запуску завершена.';

{ Execution states }

RSExtractingProjects = 'Определение проектов...';
RSProjectsExtracted = 'Список проектов составлен.';
//
RSExcludingProjects = 'Исключение проектов...';
RSProjectExcluded = 'Исключён проект: %s';
RSProjectsExcluded = 'Список проектов актуализирован.';
//
RSRunningFixInsight = 'Статический анализ кода...';
RSFixInsightRan = 'Анализ завершён.';
//
RSParsingReports = 'Разбор отчётов статического анализа кода...';
RSReportNotFound = 'Не найден отчёт для проекта: %s';
RSReportsParsed = 'Разбор завершён.';
//
RSExcludingUnits = 'Фильтрация результатов статического анализа кода от исключаемых модулей...';
RSUnitExcluded = 'Исключён модуль: %s';
RSUnitsExcluded = 'Результаты актуализированы.';
//
RSBuildingReport = 'Построение отчёта...';
RSReportBuilt = 'Отчёт построен.';
//
RSMakingArchive = 'Этап упаковки отчёта в архив...';
RSArchiveMade = 'Этап пройден.';
//
RSTerminating = 'Завершение работы...';
RSTerminated = 'Работа завершена.';

{ Exceptions }

RSApplicationExecutionFailed = 'Ошибка при выполнении программы.';
RSCLIOptionsProcessingFailed = 'Ошибка при обработке параметров командной строки.';
RSErroneousConfigSpecified = 'Указанный файл конфигурации содержит ошибки.';
RSNoValidConfigSpecified = 'Не был указан подходящий файл конфигурации.';
RSUnableToGenerateConfig = 'Не удалось сгенерировать файл конфигурации.';
RSUnknownInputFileType = 'Неизвестный тип входного файла.';
