{ Common }

RSReportTitle = 'FIToolkit Report';

{ Exceptions }

RSInvalidReportTemplate = 'Invalid report template.';
RSReportTemplateLoadError = 'Error during report template loading.';
RSReportTemplateParseError = 'Error during report template parsing.';

{ Message type names }

RSCodingConvention = 'Coding convention';
RSFatal = 'Code parser failure';
RSOptimization = 'Optimization';
RSTrial = 'Trial';
RSWarning = 'Warning';
