{ Common }

RSReportTitle = 'FIToolkit Report';

{ Exceptions }

RSInvalidReportTemplate = 'Неверный шаблон отчёта.';
RSReportTemplateLoadError = 'Ошибка загрузки шаблона отчёта.';
RSReportTemplateParseError = 'Ошибка разбора шаблона отчёта.';

{ Message type names }

RSCodingConvention = 'Стиль кода';
RSFatal = 'Сбой парсера';
RSOptimization = 'Оптимизация';
RSTrial = 'Пробная версия';
RSWarning = 'Предупреждение';
