{ Exceptions }

RSFIOEmptyOutputFileName = 'Empty output file name.';
RSFIOInvalidOutputFileName = 'Invalid output file name.';
RSFIOOutputDirectoryNotFound = 'Output directory not found.';
RSFIOProjectFileNotFound = 'Project file not found.';
RSFIOSettingsFileNotFound = 'FixInsight settings file not found.';

RSCDCustomTemplateFileNotFound = 'Custom template file not found.';
RSCDFixInsightExeNotFound = 'FixInsight executable not found.';
RSCDInputFileNotFound = 'Input file not found.';
RSCDInvalidExcludeProjectPattern = 'Invalid exclude project pattern: %s';
RSCDInvalidExcludeUnitPattern = 'Invalid exclude unit pattern: %s';
RSCDInvalidNonZeroExitCodeMsgCount = 'Invalid non zero exit code messages count.';
RSCDInvalidOutputFileName = 'Invalid output file name.';
RSCDOutputDirectoryNotFound = 'Output directory not found.';
RSCDSnippetSizeOutOfRange = 'Code snippet size is out of range [%d..%d].';
RSCDTempDirectoryNotFound = 'Temporary directory not found.';
