{ Exceptions }

RSFIOEmptyOutputFileName = 'Пустое имя выходного файла.';
RSFIOInvalidOutputFileName = 'Имя выходного файла содержит недопустимые символы.';
RSFIOOutputDirectoryNotFound = 'Директории выходного файла не существует.';
RSFIOProjectFileNotFound = 'Файл проекта не найден.';
RSFIOSettingsFileNotFound = 'Файл настроек FixInsight не найден.';

RSCDCustomTemplateFileNotFound = 'Файл пользовательского шаблона не найден.';
RSCDFixInsightExeNotFound = 'Исполняемый файл FixInsight не найден.';
RSCDInputFileNotFound = 'Входной файл не найден.';
RSCDInvalidExcludeProjectPattern = 'Ошибка в регулярном выражении для исключения проектов: %s';
RSCDInvalidExcludeUnitPattern = 'Ошибка в регулярном выражении для исключения модулей: %s';
RSCDInvalidNonZeroExitCodeMsgCount = 'Неверное пороговое число сообщений для ненулевого кода выхода.';
RSCDInvalidOutputFileName = 'Неверное имя выходного файла.';
RSCDOutputDirectoryNotFound = 'Выходная директория не найдена.';
RSCDSnippetSizeOutOfRange = 'Размер фрагмента кода выходит за пределы диапазона [%d..%d].';
RSCDTempDirectoryNotFound = 'Директория для временных файлов не найдена.';
