unit Test_FIToolkit.Base.Types;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,
  FIToolkit.Base.Types;

type
  // Test methods for TAssignable

  TestTAssignable = class (TTestCase)
  private
    const
      INT_TEST = 777;
    type
      TAssignableInteger = TAssignable<Integer>;
  published
    procedure TestAssigned;
    procedure TestCreate;
    procedure TestOnChange;
    procedure TestOnChanging;
    procedure TestUnassign;
    procedure TestValue;
  end;

implementation

{ TestTAssignable }

procedure TestTAssignable.TestAssigned;
begin

end;

procedure TestTAssignable.TestCreate;
begin

end;

procedure TestTAssignable.TestOnChange;
begin

end;

procedure TestTAssignable.TestOnChanging;
begin

end;

procedure TestTAssignable.TestUnassign;
begin

end;

procedure TestTAssignable.TestValue;
begin

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTAssignable.Suite);
end.
