unit Test_FIToolkit.Reports.Parser.XMLOutputParser;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  System.SysUtils,
  TestFramework,
  FIToolkit.Reports.Parser.XMLOutputParser;

type
  // Test methods for class TFixInsightXMLParser

  TestTFixInsightXMLParser = class (TGenericTestCase)
  strict private
    FFixInsightXMLParser : TFixInsightXMLParser;
  private
    function  GenerateXMLFile : TFileName;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestParse;
  end;

implementation

function TestTFixInsightXMLParser.GenerateXMLFile : TFileName;
begin
  // TODO: implement {TestTFixInsightXMLParser.GenerateXMLFile}
end;

procedure TestTFixInsightXMLParser.SetUp;
begin
  FFixInsightXMLParser := TFixInsightXMLParser.Create;
end;

procedure TestTFixInsightXMLParser.TearDown;
begin
  FreeAndNil(FFixInsightXMLParser);
end;

procedure TestTFixInsightXMLParser.TestParse;
var
  Append : Boolean;
begin
  Append := True;
  FFixInsightXMLParser.Parse(GenerateXMLFile, Append);

  // TODO: implement {TestTFixInsightXMLParser.TestParse}
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFixInsightXMLParser.Suite);

end.
