unit Test_FIToolkit.ProjectGroupParser.Parser;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework,
  FIToolkit.ProjectGroupParser.Parser;

type
  // Test methods for class TProjectGroupParser

  TestTProjectGroupParser = class(TGenericTestCase)
  strict private
    FProjectGroupParser : TProjectGroupParser;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetIncludedProjectsFiles;
  end;

implementation

uses
  System.SysUtils;

{ TestTProjectGroupParser }

procedure TestTProjectGroupParser.SetUp;
begin
  FProjectGroupParser := TProjectGroupParser.Create('');
end;

procedure TestTProjectGroupParser.TearDown;
begin
  FreeAndNil(FProjectGroupParser);
end;

procedure TestTProjectGroupParser.TestGetIncludedProjectsFiles;
begin
  //
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProjectGroupParser.Suite);

end.
