unit Test_FIToolkit.Base.FiniteStateMachine.FSM;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,
  FIToolkit.Base.FiniteStateMachine.FSM, FIToolkit.Base.Exceptions;

type
  // Test methods for class TFiniteStateMachine

  TestTFiniteStateMachine = class(TGenericTestCase)
  private
    type
      TStateType = (stStart, stState1, stState2, stState3, stFinish);
      TCommandType = (ctBegin, ctSwitchState_1to2, ctSwitchState_2to3, ctEnd);
      ETestException = class (ECustomException);

      TOnEnterStateMethod = TOnEnterStateMethod<TStateType, TCommandType>;
      TOnEnterStateProc   = TOnEnterStateProc<TStateType, TCommandType>;
      TOnExitStateMethod  = TOnExitStateMethod<TStateType, TCommandType>;
      TOnExitStateProc    = TOnExitStateProc<TStateType, TCommandType>;

      IFiniteStateMachine = IFiniteStateMachine<TStateType, TCommandType, ETestException>;
      TFiniteStateMachine = class (TFiniteStateMachine<TStateType, TCommandType, ETestException>);
    const
      START_STATE  = stStart;
      FINISH_STATE = stFinish;
  strict private
    FFiniteStateMachine: IFiniteStateMachine;
  private
    FEnterStateCalled,
    FExitStateCalled : Boolean;

    procedure OnEnterState(const PreviousState, CurrentState : TStateType; const UsedCommand : TCommandType);
    procedure OnExitState(const CurrentState, NewState : TStateType; const UsedCommand : TCommandType);
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAddTransition_NoEvents;
    procedure TestAddTransition_MethodEvents;
    procedure TestAddTransition_ProcEvents;
    procedure TestExecute;
    procedure TestGetReachableState_FromSpecifiedState;
    procedure TestGetReachableState_FromCurrentState;
    procedure TestHasTransition_FromSpecifiedState;
    procedure TestHasTransition_FromCurrentState;
    procedure TestRemoveTransition;
  end;

implementation

uses
  TestUtils,
  FIToolkit.Base.FiniteStateMachine.Exceptions;

procedure TestTFiniteStateMachine.OnEnterState(const PreviousState, CurrentState : TStateType;
  const UsedCommand : TCommandType);
begin
  FEnterStateCalled := True;
end;

procedure TestTFiniteStateMachine.OnExitState(const CurrentState, NewState : TStateType;
  const UsedCommand : TCommandType);
begin
  FExitStateCalled := True;
end;

procedure TestTFiniteStateMachine.SetUp;
begin
  FFiniteStateMachine := TFiniteStateMachine.Create(START_STATE);
  FEnterStateCalled := False;
  FExitStateCalled := False;
end;

procedure TestTFiniteStateMachine.TearDown;
begin
  FFiniteStateMachine := nil;
end;

procedure TestTFiniteStateMachine.TestAddTransition_NoEvents;
var
  ReturnValue: IFiniteStateMachine;
  OnCommand: TCommandType;
  ToState: TStateType;
  FromState: TStateType;
begin
  FromState := stStart;
  ToState := stFinish;
  OnCommand := ctEnd;

  ReturnValue := FFiniteStateMachine.AddTransition(FromState, ToState, OnCommand);

  CheckEquals(TObject(FFiniteStateMachine), TObject(ReturnValue), 'ReturnValue = FFiniteStateMachine');
  CheckTrue(ReturnValue.HasTransition(FromState, OnCommand), 'CheckTrue::HasTransition');
  CheckEquals<TStateType>(ToState, ReturnValue.GetReachableState(FromState, OnCommand),
    'GetReachableState = ToState');
  CheckException(
    procedure
    begin
      ReturnValue.AddTransition(FromState, ToState, OnCommand);
    end,
    ETestException,
    'CheckException::ETestException'
  );
end;

procedure TestTFiniteStateMachine.TestAddTransition_MethodEvents;
var
  ReturnValue: IFiniteStateMachine;
  OnExit: TOnExitStateMethod;
  OnEnter: TOnEnterStateMethod;
  OnCommand: TCommandType;
  ToState: TStateType;
  FromState: TStateType;
begin
  FromState := stState1;
  ToState := stState2;
  OnCommand := ctSwitchState_1to2;
  OnEnter := OnEnterState;
  OnExit := OnExitState;

  ReturnValue := FFiniteStateMachine.AddTransition(FromState, ToState, OnCommand,
      OnEnter, OnExit);

  CheckEquals(TObject(FFiniteStateMachine), TObject(ReturnValue), 'ReturnValue = FFiniteStateMachine');
  CheckTrue(ReturnValue.HasTransition(FromState, OnCommand), 'CheckTrue::HasTransition');
  CheckEquals<TStateType>(ToState, ReturnValue.GetReachableState(FromState, OnCommand),
    'GetReachableState = ToState');
  CheckException(
    procedure
    begin
      ReturnValue.AddTransition(FromState, ToState, OnCommand);
    end,
    ETestException,
    'CheckException::ETestException'
  );
end;

procedure TestTFiniteStateMachine.TestAddTransition_ProcEvents;
var
  ReturnValue: IFiniteStateMachine;
  OnExit: TOnExitStateProc;
  OnEnter: TOnEnterStateProc;
  OnCommand: TCommandType;
  ToState: TStateType;
  FromState: TStateType;
begin
  FromState := stState3;
  ToState := stFinish;
  OnCommand := ctEnd;
  OnEnter :=
    procedure (const PreviousState, CurrentState : TStateType; const UsedCommand : TCommandType)
    begin
      //FEnterStateCalled := True;
    end;
  OnExit :=
    procedure (const CurrentState, NewState : TStateType; const UsedCommand : TCommandType)
    begin
      //FExitStateCalled := True;
    end;

  ReturnValue := FFiniteStateMachine.AddTransition(FromState, ToState, OnCommand,
      OnEnter, OnExit);

  CheckEquals(TObject(FFiniteStateMachine), TObject(ReturnValue), 'ReturnValue = FFiniteStateMachine');
  CheckTrue(ReturnValue.HasTransition(FromState, OnCommand), 'CheckTrue::HasTransition');
  CheckEquals<TStateType>(ToState, ReturnValue.GetReachableState(FromState, OnCommand),
    'GetReachableState = ToState');
  CheckException(
    procedure
    begin
      ReturnValue.AddTransition(FromState, ToState, OnCommand);
    end,
    ETestException,
    'CheckException::ETestException'
  );
end;

procedure TestTFiniteStateMachine.TestExecute;
var
  ReturnValue: IFiniteStateMachine;
  Command: TCommandType;
begin
  // TODO: Setup method call parameters
  ReturnValue := FFiniteStateMachine.Execute(Command);
  // TODO: Validate method results
end;

procedure TestTFiniteStateMachine.TestGetReachableState_FromSpecifiedState;
const
  TARGET_STATE = stState2;
var
  ReturnValue: TStateType;
  OnCommand: TCommandType;
  FromState: TStateType;
begin
  FromState := stState1;
  OnCommand := ctSwitchState_1to2;
  FFiniteStateMachine.AddTransition(FromState, TARGET_STATE, OnCommand);

  ReturnValue := FFiniteStateMachine.GetReachableState(FromState, OnCommand);

  CheckEquals<TStateType>(TARGET_STATE, ReturnValue,
    'ReturnValue = TARGET_STATE');
  CheckException(
    procedure
    begin
      FFiniteStateMachine.GetReachableState(FINISH_STATE, ctEnd);
    end,
    ETestException,
    'CheckException::ETestException'
  );
  CheckInnerException(
    procedure
    begin
      FFiniteStateMachine.GetReachableState(FINISH_STATE, ctEnd);
    end,
    ETransitionNotFound,
    'CheckException::ETransitionNotFound'
  );
end;

procedure TestTFiniteStateMachine.TestGetReachableState_FromCurrentState;
const
  TARGET_STATE = stState1;
var
  ReturnValue: TStateType;
  OnCommand: TCommandType;
begin
  OnCommand := ctBegin;
  FFiniteStateMachine.AddTransition(START_STATE, TARGET_STATE, OnCommand);

  ReturnValue := FFiniteStateMachine.GetReachableState(OnCommand);

  CheckEquals<TStateType>(TARGET_STATE, ReturnValue,
    'ReturnValue = TARGET_STATE');
  CheckException(
    procedure
    begin
      FFiniteStateMachine.GetReachableState(FINISH_STATE, ctEnd);
    end,
    ETestException,
    'CheckException::ETestException'
  );
  CheckInnerException(
    procedure
    begin
      FFiniteStateMachine.GetReachableState(FINISH_STATE, ctEnd);
    end,
    ETransitionNotFound,
    'CheckException::ETransitionNotFound'
  );
end;

procedure TestTFiniteStateMachine.TestHasTransition_FromSpecifiedState;
const
  TARGET_STATE = stState2;
var
  ReturnValue: Boolean;
  OnCommand: TCommandType;
  FromState: TStateType;
begin
  FromState := stState1;
  OnCommand := ctSwitchState_1to2;
  FFiniteStateMachine.AddTransition(FromState, TARGET_STATE, OnCommand);

  ReturnValue := FFiniteStateMachine.HasTransition(FromState, OnCommand);
  CheckTrue(ReturnValue, 'CheckTrue::ReturnValue');

  FromState := FINISH_STATE;
  OnCommand := ctEnd;

  ReturnValue := FFiniteStateMachine.HasTransition(FromState, OnCommand);
  CheckFalse(ReturnValue, 'CheckFalse::ReturnValue');
end;

procedure TestTFiniteStateMachine.TestHasTransition_FromCurrentState;
const
  TARGET_STATE = stState1;
var
  ReturnValue: Boolean;
  OnCommand: TCommandType;
begin
  OnCommand := ctBegin;
  FFiniteStateMachine.AddTransition(START_STATE, TARGET_STATE, OnCommand);

  ReturnValue := FFiniteStateMachine.HasTransition(OnCommand);
  CheckTrue(ReturnValue, 'CheckTrue::ReturnValue');

  OnCommand := ctEnd;

  ReturnValue := FFiniteStateMachine.HasTransition(OnCommand);
  CheckFalse(ReturnValue, 'CheckFalse::ReturnValue');
end;

procedure TestTFiniteStateMachine.TestRemoveTransition;
var
  ReturnValue: IFiniteStateMachine;
  OnCommand: TCommandType;
  FromState: TStateType;
begin
  FromState := START_STATE;
  OnCommand := ctEnd;
  FFiniteStateMachine.AddTransition(FromState, FINISH_STATE, OnCommand);

  CheckTrue(FFiniteStateMachine.HasTransition(FromState, OnCommand), 'CheckTrue::HasTransition');
  ReturnValue := FFiniteStateMachine.RemoveTransition(FromState, OnCommand);

  CheckEquals(TObject(FFiniteStateMachine), TObject(ReturnValue), 'ReturnValue = FFiniteStateMachine');
  CheckFalse(ReturnValue.HasTransition(FromState, OnCommand), 'CheckFalse::HasTransition');
  CheckException(
    procedure
    begin
      ReturnValue.RemoveTransition(FromState, OnCommand);
    end,
    nil,
    'CheckException::nil'
  );
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFiniteStateMachine.Suite);
end.

