unit Test_FIToolkit.Config.Storage;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, System.IniFiles,
  FIToolkit.Config.Storage;

type
  // Test methods for class TConfigFile

  TestTConfigFile = class(TTestCase)
  strict private
    FConfigFile : TConfigFile;
  private
    function  GetTestIniFileName : TFileName;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAfterConstruction;
    procedure TestLoad;
    procedure TestSave;
  end;

implementation

function TestTConfigFile.GetTestIniFileName : TFileName;
begin
  Result := ChangeFileExt(ParamStr(0), '.ini');
end;

procedure TestTConfigFile.SetUp;
begin
  //
end;

procedure TestTConfigFile.TearDown;
begin
  FreeAndNil(FConfigFile);
end;

procedure TestTConfigFile.TestAfterConstruction;
begin
  FConfigFile.AfterConstruction;
  // TODO: Validate method results
end;

procedure TestTConfigFile.TestLoad;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FConfigFile.Load;
  // TODO: Validate method results
end;

procedure TestTConfigFile.TestSave;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FConfigFile.Save;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTConfigFile.Suite);
end.
