unit Test_FIToolkit.Reports.Builder.HTML;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,
  FIToolkit.Reports.Builder.HTML,
  TestTypes;

type

  // Test methods for class THTMLReportBuilder

  TestTHTMLReportBuilder = class (TGenericTestCase)
  private
    const
      START_TIME : TDateTimeRec = (
        Year : 2015; Month : 06; Day : 29;
        Hour : 18; Minute : 24; Second : 44;
      );
      FINISH_TIME : TDateTimeRec = (
        Year : 2016; Month : 10; Day : 31;
        Hour : 20; Minute : 35; Second : 54;
      );
  strict private
    FHTMLReportBuilder : THTMLReportBuilder;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAddFooter;
    procedure TestAddHeader;
    procedure TestAddTotalSummary;
    procedure TestAppendRecord;
    procedure TestBeginProjectSection;
    procedure TestBeginReport;
    procedure TestEndProjectSection;
    procedure TestEndReport;
    procedure TestSetTemplate;
  end;

  // Test methods for class THTMLReportTemplate

  TestTHTMLReportTemplate = class (TGenericTestCase)
    private
      const
        STR_TEMPLATE =
          {$REGION 'XML'}
          '<?xml version="1.0" encoding="UTF-8"?>' +
          '<HTMLReportTemplate>' +
          '	<CSS>' +
          '		<![CDATA[%STYLE%]]>' +
          '	</CSS>' +
          '	<Header>' +
          '		<Element>' +
          '			<![CDATA[%HEADER_ELEMENT%]]>' +
          '		</Element>' +
          '	</Header>' +
          '	<TotalSummary>' +
          '		<Element>' +
          '			<![CDATA[%TOTAL_SUMMARY_ELEMENT%]]>' +
          '		</Element>' +
          '		<TotalSummaryItem>' +
          '			<Element>' +
          '				<![CDATA[%TOTAL_SUMMARY_ITEM_ELEMENT%]]>' +
          '			</Element>' +
          '		</TotalSummaryItem>' +
          '	</TotalSummary>' +
          '	<ProjectSection>' +
          '		<Element>' +
          '			<![CDATA[%PROJECT_SECTION_ELEMENT%]]>' +
          '		</Element>' +
          '		<ProjectSummary>' +
          '			<Element>' +
          '				<![CDATA[%PROJECT_SUMMARY_ELEMENT%]]>' +
          '			</Element>' +
          '			<ProjectSummaryItem>' +
          '				<Element>' +
          '					<![CDATA[%PROJECT_SUMMARY_ITEM_ELEMENT%]]>' +
          '				</Element>' +
          '			</ProjectSummaryItem>' +
          '		</ProjectSummary>' +
          '		<ProjectMessages>' +
          '			<Element>' +
          '				<![CDATA[%PROJECT_MESSAGES_ELEMENT%]]>' +
          '			</Element>' +
          '			<Message>' +
          '				<Element>' +
          '					<![CDATA[%MESSAGE_ELEMENT%]]>' +
          '				</Element>' +
          '			</Message>' +
          '		</ProjectMessages>' +
          '	</ProjectSection>' +
          '	<Footer>' +
          '		<Element>' +
          '			<![CDATA[%FOOTER_ELEMENT%]]>' +
          '		</Element>' +
          '	</Footer>' +
          '</HTMLReportTemplate>';
          {$ENDREGION}
    type
      TTestHTMLReportTemplate = class sealed (THTMLReportTemplate);
  strict private
    FHTMLReportTemplate : TTestHTMLReportTemplate;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetCSS;
    procedure TestGetFooterElement;
    procedure TestGetHeaderElement;
    procedure TestGetMessageElement;
    procedure TestGetProjectMessagesElement;
    procedure TestGetProjectSectionElement;
    procedure TestGetProjectSummaryElement;
    procedure TestGetProjectSummaryItemElement;
    procedure TestGetTotalSummaryElement;
    procedure TestGetTotalSummaryItemElement;
  end;

  // Test methods for class THTMLReportCustomTemplate

  TestTHTMLReportCustomTemplate = class (TGenericTestCase)
  private
    function  GetTestXMLFileName : String;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCreate;
  end;

  // Test methods for class THTMLReportDefaultTemplate

  TestTHTMLReportDefaultTemplate = class (TGenericTestCase)
  published
    procedure TestCreate;
  end;

implementation

uses
  System.Classes, System.SysUtils,
  FIToolkit.Reports.Builder.Intf, FIToolkit.Reports.Builder.Types, FIToolkit.Reports.Builder.Exceptions,
  TestUtils;

{ TestTHTMLReportBuilder }

procedure TestTHTMLReportBuilder.SetUp;
begin
  FHTMLReportBuilder := THTMLReportBuilder.Create;
end;

procedure TestTHTMLReportBuilder.TearDown;
begin
  FHTMLReportBuilder.Free;
  FHTMLReportBuilder := nil;
end;

procedure TestTHTMLReportBuilder.TestAddFooter;
var
  FinishTime : TDateTime;
begin
  FinishTime := FINISH_TIME;
  FHTMLReportBuilder.AddFooter(FinishTime);
  // TODO: Validate method results
end;

procedure TestTHTMLReportBuilder.TestAddHeader;
var
  StartTime : TDateTime;
  Title : String;
begin
  StartTime := START_TIME;
  FHTMLReportBuilder.AddHeader(Title, StartTime);
  // TODO: Validate method results
end;

procedure TestTHTMLReportBuilder.TestAddTotalSummary;
var
  Items : array of TSummaryItem;
begin
  // TODO: Setup method call parameters
  FHTMLReportBuilder.AddTotalSummary(Items);
  // TODO: Validate method results
end;

procedure TestTHTMLReportBuilder.TestAppendRecord;
var
  Item : TReportRecord;
begin
  // TODO: Setup method call parameters
  FHTMLReportBuilder.AppendRecord(Item);
  // TODO: Validate method results
end;

procedure TestTHTMLReportBuilder.TestBeginProjectSection;
var
  ProjectSummary : array of TSummaryItem;
  Title : String;
begin
  // TODO: Setup method call parameters
  FHTMLReportBuilder.BeginProjectSection(Title, ProjectSummary);
  // TODO: Validate method results
end;

procedure TestTHTMLReportBuilder.TestBeginReport;
begin
  FHTMLReportBuilder.BeginReport;
  // TODO: Validate method results
end;

procedure TestTHTMLReportBuilder.TestEndProjectSection;
begin
  FHTMLReportBuilder.EndProjectSection;
  // TODO: Validate method results
end;

procedure TestTHTMLReportBuilder.TestEndReport;
begin
  FHTMLReportBuilder.EndReport;
  // TODO: Validate method results
end;

procedure TestTHTMLReportBuilder.TestSetTemplate;
begin
  CheckException(
    procedure
    begin
      FHTMLReportBuilder.SetTemplate(nil);
    end,
    EInvalidReportTemplate,
    'CheckException::EInvalidReportTemplate'
  );
end;

{ TestTHTMLReportTemplate }

procedure TestTHTMLReportTemplate.SetUp;
var
  XML : TStringStream;
begin
  XML := TStringStream.Create(STR_TEMPLATE);
  try
    FHTMLReportTemplate := TTestHTMLReportTemplate.Create(XML);
  finally
    XML.Free;
  end;
end;

procedure TestTHTMLReportTemplate.TearDown;
begin
  FHTMLReportTemplate.Free;
  FHTMLReportTemplate := nil;
end;

procedure TestTHTMLReportTemplate.TestGetCSS;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetCSS;

  CheckEquals('%STYLE%', ReturnValue, 'ReturnValue = %STYLE%');
end;

procedure TestTHTMLReportTemplate.TestGetFooterElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetFooterElement;

  CheckEquals('%FOOTER_ELEMENT%', ReturnValue, 'ReturnValue = %FOOTER_ELEMENT%');
end;

procedure TestTHTMLReportTemplate.TestGetHeaderElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetHeaderElement;

  CheckEquals('%HEADER_ELEMENT%', ReturnValue, 'ReturnValue = %HEADER_ELEMENT%');
end;

procedure TestTHTMLReportTemplate.TestGetMessageElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetMessageElement;

  CheckEquals('%MESSAGE_ELEMENT%', ReturnValue, 'ReturnValue = %MESSAGE_ELEMENT%');
end;

procedure TestTHTMLReportTemplate.TestGetProjectMessagesElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetProjectMessagesElement;

  CheckEquals('%PROJECT_MESSAGES_ELEMENT%', ReturnValue, 'ReturnValue = %PROJECT_MESSAGES_ELEMENT%');
end;

procedure TestTHTMLReportTemplate.TestGetProjectSectionElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetProjectSectionElement;

  CheckEquals('%PROJECT_SECTION_ELEMENT%', ReturnValue, 'ReturnValue = %PROJECT_SECTION_ELEMENT%');
end;

procedure TestTHTMLReportTemplate.TestGetProjectSummaryElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetProjectSummaryElement;

  CheckEquals('%PROJECT_SUMMARY_ELEMENT%', ReturnValue, 'ReturnValue = %PROJECT_SUMMARY_ELEMENT%');
end;

procedure TestTHTMLReportTemplate.TestGetProjectSummaryItemElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetProjectSummaryItemElement;

  CheckEquals('%PROJECT_SUMMARY_ITEM_ELEMENT%', ReturnValue, 'ReturnValue = %PROJECT_SUMMARY_ITEM_ELEMENT%');
end;

procedure TestTHTMLReportTemplate.TestGetTotalSummaryElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetTotalSummaryElement;

  CheckEquals('%TOTAL_SUMMARY_ELEMENT%', ReturnValue, 'ReturnValue = %TOTAL_SUMMARY_ELEMENT%');
end;

procedure TestTHTMLReportTemplate.TestGetTotalSummaryItemElement;
var
  ReturnValue : String;
begin
  ReturnValue := FHTMLReportTemplate.GetTotalSummaryItemElement;

  CheckEquals('%TOTAL_SUMMARY_ITEM_ELEMENT%', ReturnValue, 'ReturnValue = %TOTAL_SUMMARY_ITEM_ELEMENT%');
end;

{ TestTHTMLReportCustomTemplate }

function TestTHTMLReportCustomTemplate.GetTestXMLFileName : String;
begin
  Result := TestDataDir + ClassName + '.xml';
end;

procedure TestTHTMLReportCustomTemplate.SetUp;
var
  L : TStringList;
begin
  L := TStringList.Create;
  try
    L.Text := TestTHTMLReportTemplate.STR_TEMPLATE;
    L.SaveToFile(GetTestXMLFileName);
  finally
    L.Free;
  end;
end;

procedure TestTHTMLReportCustomTemplate.TearDown;
begin
  DeleteFile(GetTestXMLFileName);
end;

procedure TestTHTMLReportCustomTemplate.TestCreate;
begin
  CheckException(
    procedure
    begin
      THTMLReportCustomTemplate.Create(String.Empty);
    end,
    EReportTemplateLoadError,
    'CheckException::EReportTemplateLoadError'
  );

  CheckException(
    procedure
    begin
      THTMLReportCustomTemplate.Create(GetTestXMLFileName).Free;
    end,
    nil,
    'CheckException::nil'
  );
end;

{ TestTHTMLReportDefaultTemplate }

procedure TestTHTMLReportDefaultTemplate.TestCreate;
begin
  CheckException(
    procedure
    begin
      THTMLReportDefaultTemplate.Create;
    end,
    EReportTemplateLoadError,
    'CheckException::EReportTemplateLoadError'
  );
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTHTMLReportBuilder.Suite);
  RegisterTest(TestTHTMLReportTemplate.Suite);
  RegisterTest(TestTHTMLReportCustomTemplate.Suite);
  RegisterTest(TestTHTMLReportDefaultTemplate.Suite);

end.
