{ Plain text output }

RSPTOMainThreadName = 'MAIN';

RSPTOMsgTypeDescDebug   = '( DEBUG ) ';
RSPTOMsgTypeDescInfo    = '( INFO  ) ';
RSPTOMsgTypeDescWarning = '(WARNING) ';
RSPTOMsgTypeDescError   = '( ERROR ) ';
RSPTOMsgTypeDescFatal   = '( FATAL ) ';
RSPTOMsgTypeDescExtreme = '(EXTREME) ';

RSPTOSectionBeginningPrefix = '   -> ';
RSPTOSectionEndingPrefix = '   <- ';
RSPTOSectionIndentStr = '  ';
